import nodemailer from "nodemailer";

export interface EmailAttachment {
  filename: string;
  content?: string | Buffer;
  path?: string;
  contentType?: string;
}

export interface EmailOptions {
  to: string;
  subject: string;
  html: string;
  text?: string;
  category?: string;
  attachments?: EmailAttachment[];
}

const EMAIL_LOGS_KEY = "flexsell-email-logs-storage";

export function logEmailToStorage(emailOpt: EmailOptions): void {
  if (typeof window !== "undefined") {
    try {
      const raw = localStorage.getItem(EMAIL_LOGS_KEY);
      const logs = raw ? JSON.parse(raw) : [];
      logs.unshift({
        id: `email-${Date.now()}`,
        to: emailOpt.to,
        subject: emailOpt.subject,
        category: emailOpt.category || "general",
        sentAt: new Date().toISOString(),
        previewText: emailOpt.subject,
      });
      localStorage.setItem(EMAIL_LOGS_KEY, JSON.stringify(logs.slice(0, 50)));
    } catch {
      // ignore
    }
  }
}

export function renderStandardEmailFooter(docTypeLabel: string = "document", orderId?: string, targetUrlOverride?: string): string {
  const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000").replace(/\/$/, "");
  const isOrderRelated = Boolean(orderId && orderId.trim());
  const labelLower = docTypeLabel.toLowerCase();
  const isAdminAlert = labelLower.includes("admin") || labelLower.includes("buyer profile update alert") || labelLower.includes("rfq alert");

  let targetPath = "/client/dashboard";
  let actionText = "Access your B2B account, buyer profile & catalog online:";
  let buttonText = "📊 Go to Account Dashboard";

  if (isAdminAlert) {
    if (isOrderRelated) {
      targetPath = `/admin/orders/${orderId}`;
      actionText = "Manage and fulfill this purchase order in Admin Panel:";
      buttonText = `📦 View Order #${orderId} in Admin`;
    } else if (labelLower.includes("rfq") || labelLower.includes("inquiry")) {
      targetPath = "/admin/inquiries";
      actionText = "Review and respond to this inquiry in Admin Panel:";
      buttonText = "✉️ View Inquiries in Admin";
    } else if (labelLower.includes("buyer") || labelLower.includes("customer")) {
      targetPath = "/admin/customers";
      actionText = "Review buyer accounts in Admin Panel:";
      buttonText = "👥 View Customers in Admin";
    } else {
      targetPath = "/admin";
      actionText = "Access Admin Control Center online:";
      buttonText = "⚙️ Go to Admin Dashboard";
    }
  } else if (isOrderRelated) {
    targetPath = `/client/orders/${orderId}`;
    actionText = "Want to view order details, shipment tracking & tax documents online?";
    buttonText = "📦 View & Track Order Details";
  }

  if (targetUrlOverride) {
    targetPath = targetUrlOverride;
  }

  const redirectUrl = `${siteUrl}/login?callbackUrl=${encodeURIComponent(targetPath)}`;

  return `
    <div style="margin-top: 32px; border-top: 2px solid #e2e8f0; padding-top: 20px; font-family: Arial, sans-serif; background-color: #f8fafc; border-radius: 8px; padding: 20px;">
      <!-- System Generated Instruction & Notice -->
      <div style="margin-bottom: 16px; padding: 12px 16px; background-color: #f1f5f9; border-left: 4px solid #6366f1; border-radius: 4px;">
        <p style="margin: 0; font-size: 13px; color: #475569; font-weight: 500; line-height: 1.5;">
          ℹ️ <strong>System Generated Notice & Instruction:</strong><br/>
          This ${docTypeLabel} is electronically generated by the FlexSell Wholesale B2B System. No physical signature is required.
        </p>
      </div>

      <!-- Contextual Direct Action & Redirect Link Button -->
      <div style="text-align: center; margin: 20px 0 16px 0;">
        <p style="font-size: 14px; color: #334155; margin-bottom: 12px; font-weight: 600;">
          ${actionText}
        </p>
        <a href="${redirectUrl}" style="background-color: #0f172a; color: #10b981; text-decoration: none; padding: 12px 24px; border-radius: 6px; font-weight: bold; font-size: 14px; display: inline-block; border: 1px solid #10b981;">
          ${buttonText}
        </a>
        <p style="font-size: 12px; color: #64748b; margin-top: 8px;">
          Direct link: <a href="${redirectUrl}" style="color: #3b82f6; text-decoration: underline;">${redirectUrl}</a>
        </p>
      </div>

      <!-- Corporate Footer -->
      <div style="border-top: 1px solid #cbd5e1; padding-top: 12px; text-align: center; font-size: 12px; color: #94a3b8;">
        <p style="margin: 0 0 4px 0;"><strong>FlexSell Wholesale B2B Platform</strong></p>
        <p style="margin: 0;">Support Email: <a href="mailto:support@flexsellwholesale.com" style="color: #3b82f6; text-decoration: underline;">support@flexsellwholesale.com</a> | Registered Wholesale B2B Supplier</p>
        <p style="margin: 4px 0 0 0; font-size: 11px; color: #cbd5e1;">© 2026 FlexSell Wholesale. All rights reserved.</p>
      </div>
    </div>
  `;
}

export function buildValidPdfBuffer(data: any, typeLabel: string): Buffer {
  const rawId = (data._id || data.id || "FSW-DOC").toString();
  const docNumber = rawId.replace(/[^a-zA-Z0-9_-]/g, "");
  const customerName = (data.customerName || data.shippingAddress?.name || "Valued Customer").replace(/[()\\]/g, "");
  const customerCompany = (data.company || data.shippingAddress?.company || "").replace(/[()\\]/g, "");
  const addressObj = data.shippingAddress || {};
  const customerAddress = (addressObj.address ? `${addressObj.address}, ${addressObj.city || ''}, ${addressObj.state || ''} - ${addressObj.pinCode || ''}` : (data.address || "N/A")).replace(/[()\\]/g, "");
  const customerGstin = (data.gstin || addressObj.gstin || "N/A").replace(/[()\\]/g, "");
  const dateStr = new Date(data.createdAt || Date.now()).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
  const amount = Number(data.amount || data.total || 0);
  const paymentStatus = (data.paymentStatus || "Paid / Recorded").replace(/[()\\]/g, "");

  const items: any[] = data.items || [];
  let streamCommands = "";
  
  // 1. Header Banner & Title
  streamCommands += "q 0.06 0.09 0.16 rg 40 710 532 50 re f Q\n";
  streamCommands += "BT /F1 16 Tf 1 0 0 1 55 730 Tm 1 1 1 rg (FLEXSELL WHOLESALE B2B) Tj ET\n";
  streamCommands += `BT /F1 13 Tf 1 0 0 1 350 730 Tm 0.06 0.73 0.51 rg (${typeLabel.toUpperCase().substring(0, 22)}) Tj ET\n`;
  streamCommands += `BT /F2 10 Tf 1 0 0 1 350 716 Tm 0.80 0.85 0.90 rg (#${docNumber}) Tj ET\n`;

  // 2. Buyer & Seller Details Box
  streamCommands += "q 0.97 0.98 0.99 rg 40 600 255 95 re f Q\n";
  streamCommands += "q 0.85 0.90 0.95 RG 1 w 40 600 255 95 re S Q\n";
  streamCommands += "BT /F1 10 Tf 1 0 0 1 50 678 Tm 0.06 0.09 0.16 rg (BILLED & SHIPPED TO:) Tj ET\n";
  streamCommands += `BT /F1 10 Tf 1 0 0 1 50 664 Tm 0.1 0.1 0.1 rg (${customerName.substring(0, 35)}) Tj ET\n`;
  if (customerCompany) {
    streamCommands += `BT /F2 9 Tf 1 0 0 1 50 650 Tm 0.3 0.3 0.3 rg (Company: ${customerCompany.substring(0, 35)}) Tj ET\n`;
  }
  streamCommands += `BT /F2 9 Tf 1 0 0 1 50 636 Tm 0.3 0.3 0.3 rg (Address: ${customerAddress.substring(0, 40)}) Tj ET\n`;
  streamCommands += `BT /F2 9 Tf 1 0 0 1 50 622 Tm 0.3 0.3 0.3 rg (GSTIN: ${customerGstin}) Tj ET\n`;

  streamCommands += "q 0.97 0.98 0.99 rg 317 600 255 95 re f Q\n";
  streamCommands += "q 0.85 0.90 0.95 RG 1 w 317 600 255 95 re S Q\n";
  streamCommands += "BT /F1 10 Tf 1 0 0 1 327 678 Tm 0.06 0.09 0.16 rg (SUPPLIER DETAILS:) Tj ET\n";
  streamCommands += "BT /F1 10 Tf 1 0 0 1 327 664 Tm 0.1 0.1 0.1 rg (FlexSell Wholesale B2B Platform) Tj ET\n";
  streamCommands += "BT /F2 9 Tf 1 0 0 1 327 650 Tm 0.3 0.3 0.3 rg (GSTIN: 23AAACF1001M1Z5) Tj ET\n";
  streamCommands += `BT /F2 9 Tf 1 0 0 1 327 636 Tm 0.3 0.3 0.3 rg (Issue Date: ${dateStr}) Tj ET\n`;
  streamCommands += `BT /F2 9 Tf 1 0 0 1 327 622 Tm 0.3 0.3 0.3 rg (Status: ${paymentStatus}) Tj ET\n`;

  // 3. Items Table Header
  streamCommands += "q 0.06 0.09 0.16 rg 40 565 532 22 re f Q\n";
  streamCommands += "BT /F1 9 Tf 1 0 0 1 48 572 Tm 1 1 1 rg (#) Tj ET\n";
  streamCommands += "BT /F1 9 Tf 1 0 0 1 70 572 Tm 1 1 1 rg (ITEM DESCRIPTION) Tj ET\n";
  streamCommands += "BT /F1 9 Tf 1 0 0 1 300 572 Tm 1 1 1 rg (HSN) Tj ET\n";
  streamCommands += "BT /F1 9 Tf 1 0 0 1 360 572 Tm 1 1 1 rg (UNIT PRICE) Tj ET\n";
  streamCommands += "BT /F1 9 Tf 1 0 0 1 450 572 Tm 1 1 1 rg (QTY) Tj ET\n";
  streamCommands += "BT /F1 9 Tf 1 0 0 1 500 572 Tm 1 1 1 rg (TOTAL) Tj ET\n";

  // 4. Items Rows
  let currentY = 545;
  const maxRows = Math.min(items.length, 12);
  
  if (items.length === 0) {
    streamCommands += `BT /F2 9 Tf 1 0 0 1 70 ${currentY} Tm 0.3 0.3 0.3 rg (Standard Order Line Items) Tj ET\n`;
    streamCommands += `BT /F1 9 Tf 1 0 0 1 500 ${currentY} Tm 0.1 0.1 0.1 rg (Rs. ${amount.toLocaleString("en-IN")}) Tj ET\n`;
    currentY -= 20;
  } else {
    for (let i = 0; i < maxRows; i++) {
      const item = items[i];
      const title = (item.product?.title || item.product?.name || item.name || `Item #${i + 1}`).replace(/[()\\]/g, "").substring(0, 38);
      const qty = item.quantity || 1;
      const price = Number(item.pricePerUnit || item.price || 0);
      const itemTotal = price * qty;
      const hsn = item.product?.hsnCode || "3924";

      if (i % 2 === 1) {
        streamCommands += `q 0.97 0.98 0.99 rg 40 ${currentY - 4} 532 18 re f Q\n`;
      }
      streamCommands += `q 0.90 0.92 0.95 RG 0.5 w 40 ${currentY - 4} m 572 ${currentY - 4} l S Q\n`;

      streamCommands += `BT /F2 9 Tf 1 0 0 1 48 ${currentY} Tm 0.3 0.3 0.3 rg (${i + 1}) Tj ET\n`;
      streamCommands += `BT /F1 9 Tf 1 0 0 1 70 ${currentY} Tm 0.1 0.1 0.1 rg (${title}) Tj ET\n`;
      streamCommands += `BT /F2 9 Tf 1 0 0 1 300 ${currentY} Tm 0.3 0.3 0.3 rg (${hsn}) Tj ET\n`;
      streamCommands += `BT /F2 9 Tf 1 0 0 1 360 ${currentY} Tm 0.1 0.1 0.1 rg (Rs. ${price.toLocaleString("en-IN")}) Tj ET\n`;
      streamCommands += `BT /F2 9 Tf 1 0 0 1 455 ${currentY} Tm 0.1 0.1 0.1 rg (${qty}) Tj ET\n`;
      streamCommands += `BT /F1 9 Tf 1 0 0 1 500 ${currentY} Tm 0.1 0.1 0.1 rg (Rs. ${itemTotal.toLocaleString("en-IN")}) Tj ET\n`;

      currentY -= 20;
    }
  }

  // 5. Total Box
  currentY -= 10;
  streamCommands += `q 0.92 0.99 0.96 rg 320 ${currentY - 25} 252 30 re f Q\n`;
  streamCommands += `q 0.06 0.73 0.51 RG 1.5 w 320 ${currentY - 25} 252 30 re S Q\n`;
  streamCommands += `BT /F1 11 Tf 1 0 0 1 330 ${currentY - 14} Tm 0.02 0.37 0.27 rg (GRAND TOTAL AMOUNT:) Tj ET\n`;
  streamCommands += `BT /F1 12 Tf 1 0 0 1 475 ${currentY - 14} Tm 0.02 0.37 0.27 rg (Rs. ${amount.toLocaleString("en-IN")}) Tj ET\n`;

  // 6. System Instruction Footer
  const footerY = 80;
  streamCommands += `q 0.95 0.96 0.98 rg 40 ${footerY} 532 45 re f Q\n`;
  streamCommands += `q 0.38 0.40 0.95 RG 1 w 40 ${footerY} 532 45 re S Q\n`;
  streamCommands += `BT /F1 9 Tf 1 0 0 1 50 ${footerY + 30} Tm 0.25 0.29 0.90 rg (SYSTEM GENERATED DOCUMENT NOTICE & INSTRUCTION:) Tj ET\n`;
  streamCommands += `BT /F2 8 Tf 1 0 0 1 50 ${footerY + 16} Tm 0.2 0.25 0.35 rg (This ${typeLabel} is electronically generated by FlexSell Wholesale B2B System. No physical signature required.) Tj ET\n`;
  streamCommands += `BT /F2 8 Tf 1 0 0 1 50 ${footerY + 4} Tm 0.4 0.45 0.55 rg (Log in to your FlexSell Buyer Dashboard to track real-time shipment status & print official GST invoices.) Tj ET\n`;

  const streamBuf = Buffer.from(streamCommands, "utf-8");

  const o1 = "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n";
  const o2 = "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n";
  const o3 = "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>\nendobj\n";
  const o4 = "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n";
  const o5 = "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n";
  const o6 = `6 0 obj\n<< /Length ${streamBuf.length} >>\nstream\n${streamCommands}\nendstream\nendobj\n`;

  const parts = [
    "%PDF-1.4\n",
    o1, o2, o3, o4, o5, o6
  ];

  let currentOffset = 0;
  const offsets: number[] = [];
  
  for (let i = 1; i <= 6; i++) {
    offsets[i] = currentOffset;
    currentOffset += Buffer.byteLength(parts[i], "utf-8");
  }

  const headerLen = Buffer.byteLength(parts[0], "utf-8");
  for (let i = 1; i <= 6; i++) {
    offsets[i] += headerLen;
  }

  const startXref = headerLen + currentOffset;

  let xrefStr = `xref\n0 7\n0000000000 65535 f \n`;
  for (let i = 1; i <= 6; i++) {
    xrefStr += String(offsets[i]).padStart(10, "0") + " 00000 n \n";
  }
  xrefStr += `trailer\n<< /Size 7 /Root 1 0 R >>\nstartxref\n${startXref}\n%%EOF\n`;

  const fullPdfString = parts.join("") + xrefStr;
  return Buffer.from(fullPdfString, "utf-8");
}

export function generateDocumentAttachments(data: any, typeLabel: string): EmailAttachment[] {
  const rawId = (data._id || data.id || "FSW-DOC").toString();
  const docNumber = rawId.replace(/[^a-zA-Z0-9_-]/g, "");
  const customerName = data.customerName || data.shippingAddress?.name || "Valued Customer";
  const customerCompany = data.company || data.shippingAddress?.company || "";
  const addressObj = data.shippingAddress || {};
  const customerAddress = addressObj.address ? `${addressObj.address}, ${addressObj.city || ''}, ${addressObj.state || ''} - ${addressObj.pinCode || ''}` : (data.address || "N/A");
  const customerGstin = data.gstin || addressObj.gstin || "N/A";
  const dateStr = new Date(data.createdAt || Date.now()).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
  const amount = Number(data.amount || data.total || 0);

  const items: any[] = data.items || [];
  const itemRows = items.map((item: any, idx: number) => {
    const title = item.product?.title || item.product?.name || item.name || `Item #${idx + 1}`;
    const qty = item.quantity || 1;
    const price = Number(item.pricePerUnit || item.price || 0);
    const itemTotal = price * qty;
    const hsn = item.product?.hsnCode || "3924";
    const gstRate = item.product?.gstRate || 18;
    return `
      <tr>
        <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 13px;">${idx + 1}</td>
        <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 13px;"><strong>${title}</strong></td>
        <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 13px; text-align: center;">${hsn} (${gstRate}%)</td>
        <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 13px; text-align: right;">₹${price.toLocaleString("en-IN")}</td>
        <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 13px; text-align: center;">${qty}</td>
        <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 13px; text-align: right; font-weight: bold;">₹${itemTotal.toLocaleString("en-IN")}</td>
      </tr>
    `;
  }).join("");

  const docHtml = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8" />
      <title>${typeLabel}_${docNumber}</title>
      <style>
        body { font-family: 'Helvetica Neue', Arial, sans-serif; margin: 0; padding: 24px; color: #1e293b; background-color: #ffffff; }
        .invoice-box { max-width: 800px; margin: auto; padding: 30px; border: 1px solid #cbd5e1; border-radius: 8px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }
        .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #0f172a; padding-bottom: 16px; margin-bottom: 24px; }
        .brand { font-size: 24px; font-weight: bold; color: #0f172a; }
        .doc-type { font-size: 18px; font-weight: bold; color: #10b981; text-transform: uppercase; letter-spacing: 1px; }
        .details-grid { display: table; width: 100%; margin-bottom: 24px; }
        .box { display: table-cell; width: 50%; vertical-align: top; background: #f8fafc; padding: 14px; border-radius: 6px; font-size: 13px; line-height: 1.5; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 24px; margin-top: 16px; }
        th { background-color: #0f172a; color: #ffffff; padding: 10px; font-size: 12px; text-transform: uppercase; text-align: left; }
        .total-box { text-align: right; font-size: 16px; font-weight: bold; margin-top: 16px; padding: 14px; background-color: #ecfdf5; border-radius: 6px; color: #065f46; border: 1px solid #10b981; }
        .footer { margin-top: 32px; border-top: 1px solid #e2e8f0; padding-top: 16px; text-align: center; font-size: 11px; color: #64748b; }
      </style>
    </head>
    <body>
      <div class="invoice-box">
        <div class="header">
          <div class="brand">FlexSell Wholesale B2B</div>
          <div class="doc-type">${typeLabel} #${docNumber}</div>
        </div>

        <div class="details-grid">
          <div class="box">
            <strong style="color: #0f172a;">Billed & Shipped To:</strong><br/>
            <strong>${customerName}</strong> ${customerCompany ? `(${customerCompany})` : ''}<br/>
            Address: ${customerAddress}<br/>
            GSTIN: ${customerGstin}
          </div>
          <div class="box" style="border-left: 10px solid transparent;">
            <strong style="color: #0f172a;">Supplier / Seller:</strong><br/>
            <strong>FlexSell Wholesale B2B Platform</strong><br/>
            GSTIN: 23AAACF1001M1Z5<br/>
            Issue Date: ${dateStr}<br/>
            Payment Status: ${data.paymentStatus || 'Paid / Recorded'}
          </div>
        </div>

        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Item Description</th>
              <th style="text-align: center;">HSN (GST)</th>
              <th style="text-align: right;">Unit Price</th>
              <th style="text-align: center;">Qty</th>
              <th style="text-align: right;">Total</th>
            </tr>
          </thead>
          <tbody>
            ${itemRows || `<tr><td colspan="6" style="padding:12px; text-align:center;">Standard Order Line Items</td></tr>`}
          </tbody>
        </table>

        <div class="total-box">
          Grand Total Amount: ₹${amount.toLocaleString("en-IN")}
        </div>

        <div class="footer">
          Notice: This ${typeLabel} is electronically generated by FlexSell Wholesale B2B System and requires no physical signature.<br/>
          FlexSell Wholesale • Support Email: support@flexsellwholesale.com • Official Document #${docNumber}
        </div>
      </div>
    </body>
    </html>
  `;

  const safeFilename = `${typeLabel.replace(/\s+/g, "_")}_${docNumber}`;
  const pdfBuffer = buildValidPdfBuffer(data, typeLabel);

  return [
    {
      filename: `${safeFilename}.pdf`,
      content: pdfBuffer,
      contentType: "application/pdf"
    },
    {
      filename: `${safeFilename}.html`,
      content: docHtml,
      contentType: "text/html"
    }
  ];
}

function cleanPassword(pass?: string): string {
  if (!pass) return "";
  return pass.trim().replace(/^["']|["']$/g, "").replace(/\s+/g, "");
}

function getSmtpConfig() {
  const isProd = process.env.NODE_ENV === "production";
  const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || process.env.VERCEL_URL || "").toLowerCase();
  const providerEnv = (process.env.SMTP_PROVIDER || "").toLowerCase();

  // 1. Pre-defined ZeptoMail Configuration (Fallback)
  const zeptoConfig = {
    host: "smtp.zeptomail.in",
    port: 465,
    user: process.env.SMTP_USER || "emailapikey",
    pass: process.env.SMTP_PASS || (isProd ? "" : cleanPassword("PHtE6r1fE+7piGUp+hFR4/G4QpWkZoMq/7tmKggWtIdLCPRRTE0H+Y8oxj+2rxgqUaIQFaHKnI8+tezNuumNIznkYGkdDWqyqK3sx/VYSPOZsbq6x00asFwYcULVU4PmdNFj1CTRu93TNA==")),
    from: process.env.SMTP_FROM || `"FlexSell Wholesale Support" <noreply@flexsellwholesale.com>`,
    provider: "ZeptoMail"
  };

  // 2. Pre-defined Gmail Configuration (Localhost / Development Fallback)
  const gmailConfig = {
    host: "smtp.gmail.com",
    port: 465,
    user: process.env.SMTP_USER || "kuldeepmaurya4296@gmail.com",
    pass: process.env.SMTP_PASS || (isProd ? "" : cleanPassword("jtns mwcp yteo ibxq")),
    from: process.env.SMTP_FROM || `"FlexSell Wholesale Support" <kuldeepmaurya4296@gmail.com>`,
    provider: "Gmail"
  };

  // 3. Explicit Environment Override (from .env.local)
  if (process.env.SMTP_HOST) {
    const host = process.env.SMTP_HOST.trim();
    const isZepto = host.includes("zeptomail");
    const isGmail = host.includes("gmail");
    
    // Explicit environment variables take precedence
    const user = (process.env.SMTP_USER || (isZepto ? zeptoConfig.user : gmailConfig.user)).trim();
    const rawPass = process.env.SMTP_PASS || (isZepto ? zeptoConfig.pass : gmailConfig.pass);
    const pass = isGmail ? cleanPassword(rawPass) : rawPass.trim().replace(/^["']|["']$/g, "");

    const defaultFrom = isGmail
      ? `"FlexSell Wholesale Support" <${user}>`
      : isZepto
      ? zeptoConfig.from
      : `"FlexSell Support" <${user}>`;

    return {
      host,
      port: parseInt(process.env.SMTP_PORT || "465", 10),
      user,
      pass,
      from: process.env.SMTP_FROM || defaultFrom,
      provider: isZepto ? "ZeptoMail" : isGmail ? "Gmail" : "Custom SMTP"
    };
  }

  // 4. Domain / Site URL Auto Detection
  const isZeptoDomain =
    isProd ||
    providerEnv === "zeptomail" ||
    (siteUrl.includes("flexsellwholesale.com") || siteUrl.includes("flexsellwholesale.vercel.app"));

  if (isZeptoDomain && !siteUrl.includes("localhost")) {
    return zeptoConfig;
  }

  return gmailConfig;
}

export const emailService = {
  async sendEmail(options: EmailOptions): Promise<boolean> {
    const config = getSmtpConfig();
    const smtpHost = config.host;
    const smtpUser = config.user;
    const smtpPass = config.pass;
    const smtpPort = config.port;
    const fromAddress = config.from;

    // Logging for dev / mock environment
    console.log("\n=======================================================");
    console.log(`[EMAIL DISPATCH] To: ${options.to}`);
    console.log(`[SUBJECT]: ${options.subject}`);
    console.log(`[ATTACHMENTS]: ${options.attachments ? options.attachments.map(a => a.filename).join(", ") : "None"}`);
    console.log(`[SMTP PROVIDER]: ${config.provider} (host=${smtpHost}, port=${smtpPort}, from=${fromAddress})`);
    console.log("=======================================================\n");

    logEmailToStorage(options);

    if (!smtpHost || !smtpUser || !smtpPass) {
      console.log(`[EMAIL DISPATCHER] SMTP credentials not configured. Email logged to console/storage for sandbox testing.`);
      return true;
    }

    try {
      const isGmail = smtpHost.includes("gmail");
      const transporter = nodemailer.createTransport(
        isGmail
          ? {
              service: "gmail",
              auth: {
                user: smtpUser,
                pass: smtpPass,
              },
            }
          : {
              host: smtpHost,
              port: smtpPort,
              secure: smtpPort === 465,
              auth: {
                user: smtpUser,
                pass: smtpPass,
              },
              tls: {
                rejectUnauthorized: false
              },
              connectionTimeout: 8000,
              greetingTimeout: 8000,
              socketTimeout: 8000,
            }
      );

      await transporter.sendMail({
        from: fromAddress,
        to: options.to,
        subject: options.subject,
        html: options.html,
        text: options.text || options.subject,
        attachments: options.attachments,
      });

      console.log(`[EMAIL SUCCESS - ${config.provider}] Dispatched email successfully to ${options.to}`);
      return true;
    } catch (err: any) {
      console.error(`[EMAIL DISPATCH ERROR - ${config.provider}] Failed to send email to ${options.to}:`, err.message || err);
      return false;
    }
  },


  // Get Admin recipient email
  getAdminEmail(): string {
    const candidates = [
      process.env.SUPPORT_EMAIL,
      process.env.ADMIN_EMAIL,
      process.env.SMTP_USER,
      "kuldeepmaurya4296@gmail.com"
    ];
    for (const c of candidates) {
      if (c && typeof c === "string" && c.includes("@") && !c.includes("emailapikey")) {
        return c.trim();
      }
    }
    return "kuldeepmaurya4296@gmail.com";
  },

  // 1. Pre-Registration OTP Verification Email
  async sendRegisterOtp(email: string, otpCode: string, name: string): Promise<boolean> {
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0; font-size: 24px; letter-spacing: -0.5px;">FlexSell Wholesale B2B</h2>
          <p style="color: #94a3b8; margin: 4px 0 0 0; font-size: 12px;">Email Verification Code</p>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p style="font-size: 16px; margin-top: 0;">Hello <strong>${name || "Valued Buyer"}</strong>,</p>
          <p>Thank you for initiating registration with FlexSell Wholesale. Use the following 6-digit verification code to complete your B2B account setup:</p>
          
          <div style="text-align: center; margin: 32px 0;">
            <span style="font-family: monospace; font-size: 36px; font-weight: bold; letter-spacing: 8px; color: #059669; background-color: #ecfdf5; padding: 12px 28px; border-radius: 8px; border: 2px dashed #10b981;">${otpCode}</span>
          </div>

          <p style="font-size: 13px; color: #64748b; text-align: center;">This code is valid for <strong>10 minutes</strong>. Never share this verification code with anyone.</p>
        </div>
        <div style="border-top: 1px solid #e2e8f0; padding-top: 16px; text-align: center; font-size: 12px; color: #94a3b8;">
          FlexSell Wholesale © 2026. All rights reserved.
        </div>
      </div>
    `;
    return this.sendEmail({ to: email, subject: `${otpCode} is your FlexSell Wholesale Email Verification Code`, html, category: "security" });
  },

  // 2. Welcome Email
  async sendWelcomeEmail(customer: any): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">Welcome to FlexSell Wholesale!</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello <strong>${customer.name}</strong>,</p>
          <p>Your B2B buyer account (ID: <strong>${customer._id}</strong>) is now active.</p>
          <p>You can now log in to access tiered wholesale pricing, request proforma quotes, and manage bulk purchase orders.</p>
        </div>
        ${renderStandardEmailFooter("Account Activation")}
      </div>
    `;
    return this.sendEmail({ to: customer.email, subject: "Welcome to FlexSell Wholesale - Account Activated", html: bodyHtml, category: "security" });
  },

  // 3. Admin New Buyer Alert Email
  async sendAdminNewBuyerAlert(customer: any): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">New Wholesale Buyer Registered</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello Admin,</p>
          <p>A new buyer has registered on FlexSell Wholesale:</p>
          <ul>
            <li><strong>Name:</strong> ${customer.name}</li>
            <li><strong>Email:</strong> ${customer.email}</li>
            <li><strong>Company:</strong> ${customer.company || "N/A"}</li>
            <li><strong>ID:</strong> ${customer._id}</li>
          </ul>
        </div>
        ${renderStandardEmailFooter("Buyer Registration")}
      </div>
    `;
    return this.sendEmail({ to: this.getAdminEmail(), subject: `[Admin Alert] New Buyer Registered: ${customer.name}`, html: bodyHtml, category: "security" });
  },

  // 4. Order Confirmation Email
  async sendOrderConfirmationEmail(order: any, customerEmail: string): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">Order Confirmation #${order._id}</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello <strong>${order.customerName || "Valued Customer"}</strong>,</p>
          <p>Thank you for your order! We have received your wholesale purchase order <strong>#${order._id}</strong>.</p>
          <p>Total Amount: <strong>₹${Number(order.amount || order.total || 0).toLocaleString("en-IN")}</strong></p>
          <p>Payment Method: <strong>${order.paymentMethod || "N/A"}</strong> | Payment Status: <strong>${order.paymentStatus || "Pending"}</strong></p>
        </div>
        ${renderStandardEmailFooter("Order Receipt", order._id)}
      </div>
    `;
    return this.sendEmail({ to: customerEmail, subject: `Order Confirmation #${order._id} - FlexSell Wholesale`, html: bodyHtml, category: "orders" });
  },

  // 4B. Order Cancellation Email
  async sendOrderCancellationEmail(order: any, customerEmail: string): Promise<boolean> {
    const docId = (order._id || order.id || "").toString();
    const customerName = order.customerName || order.shippingAddress?.name || "Valued Customer";
    const amount = Number(order.amount || order.total || 0);

    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #ef4444; margin: 0;">Order Cancelled #${docId}</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello <strong>${customerName}</strong>,</p>
          <p>Your wholesale purchase order <strong>#${docId}</strong> has been <strong>CANCELLED</strong>.</p>
          
          <div style="background-color: #fef2f2; border-left: 4px solid #ef4444; padding: 14px; border-radius: 4px; margin: 16px 0;">
            <p style="margin: 0; font-size: 13px; color: #991b1b; font-weight: 500;">
              Notice: If any payment was collected for this order, a refund will be processed to your original payment method in accordance with our B2B cancellation policy.
            </p>
          </div>
          <p>Total Order Amount: <strong>₹${amount.toLocaleString("en-IN")}</strong></p>
        </div>
        ${renderStandardEmailFooter("Order Cancellation Notice", docId)}
      </div>
    `;
    return this.sendEmail({ to: customerEmail, subject: `Order Cancelled Notice #${docId} - FlexSell Wholesale`, html: bodyHtml, category: "orders" });
  },

  // 5. Admin New Order Alert Email
  async sendAdminNewOrderAlert(order: any): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">New Order Received #${order._id}</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello Admin,</p>
          <p>A new wholesale purchase order has been placed:</p>
          <ul>
            <li><strong>Order ID:</strong> #${order._id}</li>
            <li><strong>Buyer:</strong> ${order.customerName}</li>
            <li><strong>Total Amount:</strong> ₹${Number(order.amount || order.total || 0).toLocaleString("en-IN")}</li>
            <li><strong>Payment Status:</strong> ${order.paymentStatus}</li>
          </ul>
        </div>
        ${renderStandardEmailFooter("New Order Alert", order._id)}
      </div>
    `;
    return this.sendEmail({ to: this.getAdminEmail(), subject: `[Admin Alert] New Order #${order._id} Received`, html: bodyHtml, category: "orders" });
  },

  // 6. Order Modification Summary Email
  async sendOrderModificationEmail(order: any, changesSummary: string): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #3b82f6; margin: 0;">Order Update #${order._id}</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello <strong>${order.customerName}</strong>,</p>
          <p>Your order <strong>#${order._id}</strong> has been updated by our fulfillment team.</p>
          <div style="background-color: #f1f5f9; padding: 16px; border-radius: 8px; font-size: 14px; margin: 16px 0;">
            <strong>Details of Changes:</strong>
            <p style="margin: 8px 0 0 0;">${changesSummary}</p>
          </div>
          <p>Updated Total: <strong>₹${Number(order.amount || order.total || 0).toLocaleString("en-IN")}</strong></p>
        </div>
        ${renderStandardEmailFooter("Order Update Notice", order._id)}
      </div>
    `;
    const email = order.shippingAddress?.email || order.customerEmail || "";
    return this.sendEmail({ to: email, subject: `Update regarding Order #${order._id}`, html: bodyHtml, category: "orders" });
  },

  // 7. Shipment Tracking Email
  async sendShipmentNotificationEmail(order: any, courierName: string, trackingNumber: string, trackingUrl?: string): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">Order Shipped #${order._id}</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello <strong>${order.customerName}</strong>,</p>
          <p>Great news! Your purchase order <strong>#${order._id}</strong> has been dispatched.</p>
          <p>Courier: <strong>${courierName}</strong> | Tracking ID: <strong>${trackingNumber}</strong></p>
          ${trackingUrl ? `<p style="margin-top: 16px;"><a href="${trackingUrl}" style="background-color: #10b981; color: white; padding: 10px 20px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: bold;">Track Shipment</a></p>` : ""}
        </div>
        ${renderStandardEmailFooter("Shipment Dispatch Notice", order._id)}
      </div>
    `;
    const email = order.shippingAddress?.email || order.customerEmail || "";
    return this.sendEmail({ to: email, subject: `Shipment Dispatch Notice #${order._id}`, html: bodyHtml, category: "shipments" });
  },

  // 8. Invoice / Proforma Quote Email
  async sendInvoiceQuoteEmail(invoice: any, customerEmail: string): Promise<boolean> {
    const typeLabel = invoice.type === "invoice" ? "GST Tax Invoice" : invoice.type === "receipt" ? "Payment Receipt" : "Proforma Quote";

    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #6366f1; margin: 0;">${typeLabel} #${invoice._id}</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello <strong>${invoice.customerName || "Valued Customer"}</strong>,</p>
          <p>Your official ${typeLabel} <strong>#${invoice._id}</strong> has been issued and processed.</p>
          <p>Amount: <strong>₹${Number(invoice.amount || invoice.total || 0).toLocaleString("en-IN")}</strong></p>
        </div>
        ${renderStandardEmailFooter(typeLabel, invoice.orderId || invoice._id)}
      </div>
    `;
    return this.sendEmail({ to: customerEmail, subject: `${typeLabel} #${invoice._id} Issued`, html: bodyHtml, category: "invoices" });
  },

  // 9. Password Reset Email
  async sendPasswordResetEmail(email: string, resetLink: string): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #e11d48; margin: 0;">Password Reset Request</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello,</p>
          <p>We received a request to reset your password for your FlexSell Wholesale account. Click the link below to set a new password:</p>
          <p style="text-align: center; margin: 24px 0;">
            <a href="${resetLink}" style="background-color: #e11d48; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: bold;">Reset Password</a>
          </p>
          <p style="font-size: 12px; color: #64748b;">This link will expire in 1 hour. If you didn't request a password reset, you can safely ignore this email.</p>
        </div>
        ${renderStandardEmailFooter("Password Reset Request")}
      </div>
    `;
    return this.sendEmail({ to: email, subject: "Reset Your FlexSell Wholesale Password", html: bodyHtml, category: "security" });
  },

  // 10. Password Changed Notification
  async sendPasswordChangedEmail(email: string): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">Password Changed Successfully</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello,</p>
          <p>Your FlexSell Wholesale account password has been successfully updated.</p>
          <p style="color: #b91c1c; font-weight: bold;">If you did not make this change, please contact our support team immediately.</p>
        </div>
        ${renderStandardEmailFooter("Security Notification")}
      </div>
    `;
    return this.sendEmail({ to: email, subject: "Security Alert: Password Changed", html: bodyHtml, category: "security" });
  },

  // 11A. Profile Update Alert Email to Customer
  async sendCustomerProfileUpdatedEmail(email: string, name: string, details?: string | string[]): Promise<boolean> {
    const formattedDetails = Array.isArray(details)
      ? details.map(d => `<li style="margin-bottom: 4px;">${d}</li>`).join("")
      : details ? `<p>${details}</p>` : "";

    const customerHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">Account Profile Updated</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello <strong>${name}</strong>,</p>
          <p>Your FlexSell Wholesale account profile information was recently updated with the following details:</p>
          ${formattedDetails ? `<div style="background-color: #f8fafc; border-left: 4px solid #10b981; padding: 16px; margin: 16px 0; border-radius: 4px;"><ul>${formattedDetails}</ul></div>` : ""}
          <p style="font-size: 13px; color: #64748b;">If you did not perform this update, please contact security immediately.</p>
        </div>
        ${renderStandardEmailFooter("Profile Update Notice")}
      </div>
    `;
    return this.sendEmail({ to: email, subject: "Security Notification: Profile Updated", html: customerHtml, category: "security" });
  },

  // 11B. Profile Update Alert Email to Admin
  async sendAdminProfileUpdatedEmail(buyerName: string, buyerEmail: string, details?: string | string[]): Promise<boolean> {
    const formattedDetails = Array.isArray(details)
      ? details.map(d => `<li style="margin-bottom: 4px;">${d}</li>`).join("")
      : details ? `<p>${details}</p>` : "";

    const adminHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #3b82f6; margin: 0;">Buyer Profile Updated</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello Admin,</p>
          <p>Wholesale Buyer <strong>${buyerName}</strong> (${buyerEmail}) updated their account profile details:</p>
          ${formattedDetails ? `<div style="background-color: #f8fafc; border-left: 4px solid #3b82f6; padding: 16px; margin: 16px 0; border-radius: 4px;"><ul>${formattedDetails}</ul></div>` : ""}
        </div>
        ${renderStandardEmailFooter("Buyer Profile Update Alert")}
      </div>
    `;
    return this.sendEmail({ to: this.getAdminEmail(), subject: `[Admin Alert] Buyer Profile Updated: ${buyerName}`, html: adminHtml, category: "security" });
  },

  // Backward compatibility wrapper
  async sendProfileUpdatedEmail(email: string, name: string, details?: string | string[]): Promise<boolean> {
    const res1 = await this.sendCustomerProfileUpdatedEmail(email, name, details);
    const res2 = await this.sendAdminProfileUpdatedEmail(name, email, details);
    return res1 && res2;
  },

  // 12. Address Added/Modified Alert Email
  async sendAddressChangedEmail(email: string, name: string): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">Shipping Addresses Updated</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello <strong>${name}</strong>,</p>
          <p>A shipping address was added, updated, or removed on your FlexSell Wholesale account.</p>
        </div>
        ${renderStandardEmailFooter("Address Book Update Notice")}
      </div>
    `;
    return this.sendEmail({ to: email, subject: "Security Notification: Addresses Updated", html: bodyHtml, category: "security" });
  },

  // 13. Payment Status Changed Email
  async sendPaymentStatusEmail(order: any, customerEmail: string): Promise<boolean> {
    const isPaid = order.paymentStatus === "Paid" || order.paymentStatus === "Completed";
    const paymentNotice = isPaid
      ? `<div style="background-color: #ecfdf5; border: 1px dashed #10b981; padding: 16px; border-radius: 8px; margin: 16px 0;">
           <p style="margin: 0; color: #065f46; font-weight: bold;">✓ Payment Recorded & Verified</p>
           <p style="margin: 4px 0 0 0; font-size: 13px; color: #047857;">Your payment has been successfully recorded. You can view your order status & printable GST Tax Invoice online from your buyer dashboard.</p>
         </div>`
      : "";

    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">Order #${order._id} Update</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello <strong>${order.customerName || "Valued Customer"}</strong>,</p>
          <p>The status for your wholesale purchase order <strong>#${order._id}</strong> is now: <strong>${order.status || "Updated"}</strong>.</p>
          <p>Payment Status: <strong>${order.paymentStatus || "Pending"}</strong> | Total Amount: <strong>₹${Number(order.amount || order.total || 0).toLocaleString("en-IN")}</strong></p>
          ${paymentNotice}
        </div>
        ${renderStandardEmailFooter("Payment Receipt & Invoice Status", order._id)}
      </div>
    `;
    return this.sendEmail({ to: customerEmail, subject: `Order #${order._id} Status & Payment Update`, html: bodyHtml, category: "payments" });
  },

  // 13B. Coupon Live Announcement Email
  async sendCouponLiveEmail(coupon: any, recipientEmail: string): Promise<boolean> {
    const discountText = coupon.discountType === "percentage" ? `${coupon.discountValue}% OFF` : `₹${coupon.discountValue} FLAT OFF`;
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 24px; text-align: center; border-radius: 8px 8px 0 0;">
          <span style="background-color: #10b981; color: #ffffff; padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px;">Exclusive Offer</span>
          <h2 style="color: #ffffff; margin: 12px 0 0 0; font-size: 22px;">New Wholesale Discount Live!</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello Valued Buyer,</p>
          <p>A new discount coupon is now live on FlexSell Wholesale for your business orders!</p>
          
          <div style="text-align: center; background-color: #ecfdf5; border: 2px dashed #10b981; padding: 20px; border-radius: 10px; margin: 24px 0;">
            <p style="margin: 0 0 8px 0; font-size: 13px; color: #047857; text-transform: uppercase; font-weight: bold;">Use Promo Code</p>
            <span style="font-family: monospace; font-size: 32px; font-weight: bold; letter-spacing: 4px; color: #059669;">${coupon.code}</span>
            <p style="margin: 8px 0 0 0; font-size: 18px; font-weight: bold; color: #0f172a;">${discountText}</p>
          </div>

          <ul style="font-size: 14px; color: #475569; padding-left: 20px; margin-bottom: 24px;">
            ${coupon.minOrderValue ? `<li>Minimum Order Value: <strong>₹${Number(coupon.minOrderValue).toLocaleString("en-IN")}</strong></li>` : ""}
            ${coupon.expiryDate ? `<li>Valid Until: <strong>${new Date(coupon.expiryDate).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</strong></li>` : ""}
          </ul>
        </div>
        ${renderStandardEmailFooter("Promotional Offer")}
      </div>
    `;
    return this.sendEmail({ to: recipientEmail, subject: `🎉 New Coupon Live: Use Code ${coupon.code} for ${discountText}`, html: bodyHtml, category: "promotions" });
  },

  // 13C. Customer Review Submitted Confirmation Email
  async sendCustomerReviewSubmittedEmail(review: any, customerEmail: string): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">Review Received</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello <strong>${review.customerName || "Valued Customer"}</strong>,</p>
          <p>Thank you for submitting your product review on FlexSell Wholesale!</p>
          <div style="background-color: #f8fafc; border-left: 4px solid #10b981; padding: 16px; margin: 16px 0; border-radius: 4px;">
            <p style="margin: 0 0 4px 0;"><strong>Rating:</strong> ${review.rating} / 5 ⭐</p>
            <p style="margin: 0;"><em>"${review.comment}"</em></p>
          </div>
          <p style="font-size: 13px; color: #64748b;">Our moderation team will review your feedback shortly before publishing it to the product catalog.</p>
        </div>
        ${renderStandardEmailFooter("Product Review Receipt")}
      </div>
    `;
    return this.sendEmail({ to: customerEmail, subject: "Thank you for your Product Review - FlexSell Wholesale", html: bodyHtml, category: "system" });
  },

  // 14. Quote Response / Negotiation Email (Accepted/Rejected)
  async sendQuoteResponseNotification(quote: any, isAccepted: boolean): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">Proforma Quote ${isAccepted ? "Accepted" : "Rejected"} #${quote._id}</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello Admin,</p>
          <p>Buyer <strong>${quote.customerName}</strong> has <strong>${isAccepted ? "ACCEPTED" : "REJECTED"}</strong> the proforma quote for order #${quote._id || quote.orderId}.</p>
          <p>Amount: <strong>₹${Number(quote.amount || quote.total || 0).toLocaleString("en-IN")}</strong></p>
        </div>
        ${renderStandardEmailFooter("Quote Response Alert", quote._id || quote.orderId)}
      </div>
    `;
    return this.sendEmail({ to: this.getAdminEmail(), subject: `[Quote Alert] Quote #${quote._id} ${isAccepted ? "Accepted" : "Rejected"}`, html: bodyHtml, category: "quotes" });
  },

  // 15. Review Submitted Alert Email to Admin
  async sendAdminReviewAlert(review: any): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #eab308; margin: 0;">New Review Submitted</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello Admin,</p>
          <p>A new product review has been submitted and is pending moderation:</p>
          <ul>
            <li><strong>Product ID:</strong> ${review.productId}</li>
            <li><strong>Customer:</strong> ${review.customerName}</li>
            <li><strong>Rating:</strong> ${review.rating} / 5</li>
            <li><strong>Title:</strong> ${review.title}</li>
            <li><strong>Comment:</strong> ${review.comment}</li>
          </ul>
        </div>
        ${renderStandardEmailFooter("Review Moderation Alert")}
      </div>
    `;
    return this.sendEmail({ to: this.getAdminEmail(), subject: `[Review Alert] Moderation Required for ${review.productId}`, html: bodyHtml, category: "system" });
  },

  // 16. Review Moderated Notification to Customer
  async sendReviewModeratedEmail(review: any, customerEmail: string): Promise<boolean> {
    const isApproved = review.status === "Approved" || review.isApproved;
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">Product Review Moderated</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello <strong>${review.customerName}</strong>,</p>
          <p>Your product review has been reviewed by our moderation team and its status is now: <strong>${isApproved ? "Approved & Published" : "Rejected"}</strong>.</p>
          <div style="border-left: 4px solid #cbd5e1; padding-left: 12px; margin-top: 12px;">
            <p><strong>Rating:</strong> ${review.rating}/5</p>
            <p><em>"${review.comment}"</em></p>
          </div>
        </div>
        ${renderStandardEmailFooter("Review Moderation Notice")}
      </div>
    `;
    return this.sendEmail({ to: customerEmail, subject: `Review Moderation Update: ${isApproved ? "Approved" : "Status Changed"}`, html: bodyHtml, category: "system" });
  },

  // 17. RFQ/Inquiry Submitted Confirmation to Customer
  async sendCustomerInquiryConfirmation(inquiry: any, customerEmail: string): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">Inquiry Received</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello <strong>${inquiry.customerName || "Valued Customer"}</strong>,</p>
          <p>Thank you for reaching out to FlexSell Wholesale. We have received your wholesale RFQ/inquiry:</p>
          <div style="background-color: #f8fafc; padding: 16px; border-radius: 8px; margin: 16px 0;">
            <strong>Subject:</strong> ${inquiry.subject}<br/>
            <strong>Message:</strong><br/>
            ${inquiry.message}
          </div>
          <p>Our sales team will review your inquiry and get back to you within 24 business hours.</p>
        </div>
        ${renderStandardEmailFooter("Inquiry Confirmation")}
      </div>
    `;
    return this.sendEmail({ to: customerEmail, subject: `Inquiry Received - Reference #${inquiry._id || "RFQ"}`, html: bodyHtml, category: "quotes" });
  },

  // 18. Admin New RFQ Alert Email
  async sendAdminInquiryAlert(inquiry: any): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">New Wholesale Inquiry Received</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello Admin,</p>
          <p>A new wholesale RFQ/inquiry has been submitted:</p>
          <ul>
            <li><strong>Customer:</strong> ${inquiry.customerName} (${inquiry.email})</li>
            <li><strong>Subject:</strong> ${inquiry.subject}</li>
            <li><strong>Message:</strong> ${inquiry.message}</li>
          </ul>
        </div>
        ${renderStandardEmailFooter("Admin RFQ Alert")}
      </div>
    `;
    return this.sendEmail({ to: this.getAdminEmail(), subject: `[RFQ Inquiry Alert] ${inquiry.subject}`, html: bodyHtml, category: "quotes" });
  },

  // 19. Inquiry Responded Email
  async sendInquiryResponseEmail(inquiry: any, responseText: string, customerEmail: string): Promise<boolean> {
    const bodyHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <div style="background-color: #0f172a; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
          <h2 style="color: #10b981; margin: 0;">Inquiry Reply</h2>
        </div>
        <div style="padding: 24px; color: #334155;">
          <p>Hello <strong>${inquiry.customerName}</strong>,</p>
          <p>An administrator has replied to your wholesale inquiry (Subject: <em>"${inquiry.subject}"</em>):</p>
          <div style="background-color: #f0fdf4; border-left: 4px solid #10b981; padding: 16px; margin: 16px 0; border-radius: 4px;">
            <strong>Reply:</strong><br/>
            ${responseText}
          </div>
        </div>
        ${renderStandardEmailFooter("Inquiry Reply Notice")}
      </div>
    `;
    return this.sendEmail({ to: customerEmail, subject: `Reply regarding Inquiry: ${inquiry.subject}`, html: bodyHtml, category: "quotes" });
  }
};
